"""
Quran Verses Dataset
Contains verses with Arabic, English translation, Urdu translation,
mood tags, and surah info.
"""

VERSES = [
    # --- SADNESS / GRIEF ---
    {
        "id": 1,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 286,
        "arabic": "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
        "english": "Allah does not burden a soul beyond that it can bear.",
        "urdu": "اللہ کسی جان پر اس کی طاقت سے زیادہ بوجھ نہیں ڈالتا۔",
        "reflection": "No matter how heavy life feels, Allah knows your limits. You are stronger than you think.",
        "moods": ["sad", "stressed", "anxious", "overwhelmed", "lost", "hopeless"],
        "keywords": "burden soul bear capacity strength limit struggle hardship",
    },
    {
        "id": 2,
        "surah_name": "Ash-Sharh",
        "surah_number": 94,
        "ayah": "5-6",
        "arabic": "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا إِنَّ مَعَ الْعُسْرِ يُسْرًا",
        "english": "For indeed, with hardship will be ease. Indeed, with hardship will be ease.",
        "urdu": "پس بے شک تکلیف کے ساتھ آسانی ہے، بے شک تکلیف کے ساتھ آسانی ہے۔",
        "reflection": "Allah repeated this twice — ease is promised not once, but always. Your difficulty will pass.",
        "moods": ["sad", "hopeless", "stressed", "anxious", "lost", "overwhelmed"],
        "keywords": "hardship ease relief difficulty struggle patience hope promise",
    },
    {
        "id": 3,
        "surah_name": "Az-Zumar",
        "surah_number": 39,
        "ayah": 53,
        "arabic": "لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ",
        "english": "Do not despair of the mercy of Allah. Indeed, Allah forgives all sins.",
        "urdu": "اللہ کی رحمت سے ناامید مت ہو، بے شک اللہ سب گناہ معاف کر دیتا ہے۔",
        "reflection": "No matter what you have done or what has happened, Allah's mercy is bigger than everything.",
        "moods": ["sad", "hopeless", "guilty", "lost", "regret", "broken"],
        "keywords": "despair mercy forgiveness hope sins repentance rahma",
    },
    {
        "id": 4,
        "surah_name": "Al-Imran",
        "surah_number": 3,
        "ayah": 139,
        "arabic": "وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ",
        "english": "Do not weaken and do not grieve, and you will be superior if you are true believers.",
        "urdu": "ہمت مت ہارو اور غمزدہ مت ہو، تم ہی غالب رہو گے اگر تم مومن ہو۔",
        "reflection": "Grief and weakness are natural — but a believer always rises. Your faith is your superpower.",
        "moods": ["sad", "demotivated", "hopeless", "broken", "lost"],
        "keywords": "grief weaken superior believer faith strength overcome sadness",
    },

    # --- ANXIETY / STRESS ---
    {
        "id": 5,
        "surah_name": "Ar-Ra'd",
        "surah_number": 13,
        "ayah": 28,
        "arabic": "أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ",
        "english": "Verily, in the remembrance of Allah do hearts find rest.",
        "urdu": "جان لو کہ اللہ کے ذکر ہی سے دلوں کو سکون ملتا ہے۔",
        "reflection": "When anxiety overwhelms you, return to Allah's remembrance. It is the only true peace.",
        "moods": ["anxious", "stressed", "restless", "worried", "panic"],
        "keywords": "hearts rest peace remembrance dhikr anxiety calm tranquility",
    },
    {
        "id": 6,
        "surah_name": "At-Talaq",
        "surah_number": 65,
        "ayah": 3,
        "arabic": "وَمَن يَتَوَكَّلْ عَلَى اللَّهِ فَهُوَ حَسْبُهُ",
        "english": "And whoever relies upon Allah — then He is sufficient for him.",
        "urdu": "اور جو اللہ پر بھروسہ کرے تو وہ اس کے لیے کافی ہے۔",
        "reflection": "Stop trying to control everything. Hand it to Allah and trust His plan completely.",
        "moods": ["anxious", "stressed", "worried", "overwhelmed", "lost"],
        "keywords": "trust tawakkul reliance sufficient rely Allah plan stress worry",
    },
    {
        "id": 7,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 45,
        "arabic": "وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
        "english": "And seek help through patience and prayer.",
        "urdu": "اور صبر اور نماز کے ذریعے مدد مانگو۔",
        "reflection": "Two of the most powerful tools Allah gave us: patience and prayer. Use them together.",
        "moods": ["anxious", "stressed", "sad", "overwhelmed", "lost"],
        "keywords": "patience prayer salah sabr help seek strength",
    },
    {
        "id": 8,
        "surah_name": "Al-Anfal",
        "surah_number": 8,
        "ayah": 11,
        "arabic": "وَيُنَزِّلُ عَلَيْكُم مِّن السَّمَاءِ مَاءً لِّيُطَهِّرَكُم بِهِ وَيُذْهِبَ عَنكُمْ رِجْزَ الشَّيْطَانِ",
        "english": "He sends down rain from the sky to purify you and remove from you the evil of Satan.",
        "urdu": "اللہ تم پر آسمان سے پانی اتارتا ہے تاکہ تمہیں پاک کرے اور شیطان کی برائی دور کرے۔",
        "reflection": "Allah continuously purifies and protects you. You are never alone in your struggles.",
        "moods": ["anxious", "stressed", "guilty", "lost"],
        "keywords": "purify protect rain shaitan evil remove cleanse comfort",
    },

    # --- ANGER ---
    {
        "id": 9,
        "surah_name": "Al-Imran",
        "surah_number": 3,
        "ayah": 134,
        "arabic": "وَالْكَاظِمِينَ الْغَيْظَ وَالْعَافِينَ عَنِ النَّاسِ",
        "english": "Those who restrain anger and pardon the people — Allah loves the doers of good.",
        "urdu": "اور غصہ پی جانے والے اور لوگوں کو معاف کر دینے والے — اللہ نیکو کاروں سے محبت کرتا ہے۔",
        "reflection": "Forgiving someone who hurt you is not weakness — it is one of the highest qualities Allah loves.",
        "moods": ["angry", "frustrated", "betrayed", "hurt"],
        "keywords": "anger restrain forgive pardon people love good control temper",
    },
    {
        "id": 10,
        "surah_name": "Fussilat",
        "surah_number": 41,
        "ayah": 34,
        "arabic": "ادْفَعْ بِالَّتِي هِيَ أَحْسَنُ فَإِذَا الَّذِي بَيْنَكَ وَبَيْنَهُ عَدَاوَةٌ كَأَنَّهُ وَلِيٌّ حَمِيمٌ",
        "english": "Repel evil with what is better; then the one who was your enemy becomes like a devoted friend.",
        "urdu": "برائی کو بہتری سے دور کرو، پھر جو تمہارا دشمن ہے وہ گہرا دوست بن جائے گا۔",
        "reflection": "Responding to hate with kindness is one of the most powerful acts a human can do.",
        "moods": ["angry", "frustrated", "betrayed", "hurt", "conflict"],
        "keywords": "repel evil good enemy friend respond kindness anger conflict",
    },

    # --- GRATITUDE / HAPPINESS ---
    {
        "id": 11,
        "surah_name": "Ibrahim",
        "surah_number": 14,
        "ayah": 7,
        "arabic": "لَئِن شَكَرْتُمْ لَأَزِيدَنَّكُمْ",
        "english": "If you are grateful, I will surely increase you in favor.",
        "urdu": "اگر تم شکر کرو گے تو میں تمہیں اور زیادہ دوں گا۔",
        "reflection": "Gratitude is not just good manners — it is a direct invitation for more blessings.",
        "moods": ["grateful", "happy", "blessed", "content", "joyful"],
        "keywords": "grateful shukr thankful increase blessings favor more gratitude",
    },
    {
        "id": 12,
        "surah_name": "Ad-Duha",
        "surah_number": 93,
        "ayah": 11,
        "arabic": "وَأَمَّا بِنِعْمَةِ رَبِّكَ فَحَدِّثْ",
        "english": "And proclaim the blessings of your Lord.",
        "urdu": "اور اپنے رب کی نعمتوں کا تذکرہ کرو۔",
        "reflection": "Talk about what Allah has given you. Sharing blessings multiplies them.",
        "moods": ["grateful", "happy", "blessed", "content"],
        "keywords": "blessings proclaim nimat Lord thankful share grateful happy",
    },
    {
        "id": 13,
        "surah_name": "An-Nahl",
        "surah_number": 16,
        "ayah": 18,
        "arabic": "وَإِن تَعُدُّوا نِعْمَةَ اللَّهِ لَا تُحْصُوهَا",
        "english": "If you tried to count the favors of Allah, you could never enumerate them.",
        "urdu": "اگر تم اللہ کی نعمتوں کو گنو تو انہیں شمار نہ کر سکو گے۔",
        "reflection": "In your happiest moments, remember: what you see is only a fraction of what you've been given.",
        "moods": ["grateful", "happy", "blessed", "content", "joyful"],
        "keywords": "count favors blessings countless Allah grateful enumerate",
    },

    # --- MOTIVATION / PERSEVERANCE ---
    {
        "id": 14,
        "surah_name": "Az-Zumar",
        "surah_number": 39,
        "ayah": 10,
        "arabic": "إِنَّمَا يُوَفَّى الصَّابِرُونَ أَجْرَهُم بِغَيْرِ حِسَابٍ",
        "english": "Indeed, the patient will be given their reward without account.",
        "urdu": "بے شک صبر کرنے والوں کو بے حساب اجر دیا جائے گا۔",
        "reflection": "Your patience and perseverance will be rewarded in ways beyond calculation. Keep going.",
        "moods": ["motivated", "perseverance", "struggling", "tired", "giving up"],
        "keywords": "patient reward perseverance sabr account unlimited struggle reward",
    },
    {
        "id": 15,
        "surah_name": "Al-Inshirah",
        "surah_number": 94,
        "ayah": 7,
        "arabic": "فَإِذَا فَرَغْتَ فَانصَبْ",
        "english": "So when you have finished, then stand up for worship.",
        "urdu": "پس جب فارغ ہو جاؤ تو محنت میں لگ جاؤ۔",
        "reflection": "Islam encourages relentless effort — rest, then rise again. Productivity with purpose.",
        "moods": ["motivated", "productive", "focused", "determined"],
        "keywords": "finished stand work effort worship productive motivated rise",
    },
    {
        "id": 16,
        "surah_name": "Al-Ankabut",
        "surah_number": 29,
        "ayah": 69,
        "arabic": "وَالَّذِينَ جَاهَدُوا فِينَا لَنَهْدِيَنَّهُمْ سُبُلَنَا",
        "english": "Those who strive for Us — We will surely guide them to Our ways.",
        "urdu": "جو لوگ ہماری راہ میں کوشش کرتے ہیں ہم انہیں اپنے راستے دکھاتے ہیں۔",
        "reflection": "Take the first step. Keep striving. Allah promises to guide those who make effort.",
        "moods": ["motivated", "lost", "confused", "seeking", "determined"],
        "keywords": "strive guide ways effort jihad path direction motivated seeking",
    },
    {
        "id": 17,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 153,
        "arabic": "إِنَّ اللَّهَ مَعَ الصَّابِرِينَ",
        "english": "Indeed, Allah is with the patient.",
        "urdu": "بے شک اللہ صبر کرنے والوں کے ساتھ ہے۔",
        "reflection": "Three words that carry infinite comfort: Allah is with you. Especially in your hardest moments.",
        "moods": ["sad", "struggling", "tired", "motivated", "perseverance", "anxious"],
        "keywords": "Allah with patient sabr together support comfort presence",
    },

    # --- LOST / GUIDANCE ---
    {
        "id": 18,
        "surah_name": "Al-Fatiha",
        "surah_number": 1,
        "ayah": 6,
        "arabic": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
        "english": "Guide us to the straight path.",
        "urdu": "ہمیں سیدھا راستہ دکھا۔",
        "reflection": "The most repeated prayer in Islam — 17 times a day. You are always allowed to ask for guidance.",
        "moods": ["lost", "confused", "seeking", "direction", "purpose"],
        "keywords": "guide straight path direction lost confused seeking purpose sirat",
    },
    {
        "id": 19,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 2,
        "arabic": "ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِّلْمُتَّقِينَ",
        "english": "This is the Book about which there is no doubt, guidance for those conscious of Allah.",
        "urdu": "یہ وہ کتاب ہے جس میں کوئی شک نہیں، ہدایت ہے پرہیزگاروں کے لیے۔",
        "reflection": "When you feel lost, come back to the Quran. Every answer you need is here.",
        "moods": ["lost", "confused", "seeking", "direction"],
        "keywords": "book guidance doubt Quran Taqwa direction lost truth",
    },
    {
        "id": 20,
        "surah_name": "Al-Duha",
        "surah_number": 93,
        "ayah": 7,
        "arabic": "وَوَجَدَكَ ضَالًّا فَهَدَىٰ",
        "english": "And He found you lost and guided you.",
        "urdu": "اور اس نے تمہیں بھٹکا ہوا پایا تو راستہ دکھایا۔",
        "reflection": "Allah has guided you before when you were lost. He will guide you again. Trust His history with you.",
        "moods": ["lost", "confused", "hopeless", "seeking"],
        "keywords": "lost guided found Allah history trust direction guidance",
    },

    # --- LONELINESS ---
    {
        "id": 21,
        "surah_name": "Al-Hadid",
        "surah_number": 57,
        "ayah": 4,
        "arabic": "وَهُوَ مَعَكُمْ أَيْنَ مَا كُنتُمْ",
        "english": "And He is with you wherever you are.",
        "urdu": "اور وہ تمہارے ساتھ ہے جہاں بھی تم ہو۔",
        "reflection": "You are never truly alone. Allah is present in every moment, every place, every breath.",
        "moods": ["lonely", "sad", "lost", "broken", "isolated"],
        "keywords": "with you wherever alone present Allah company lonely isolated",
    },
    {
        "id": 22,
        "surah_name": "Qaf",
        "surah_number": 50,
        "ayah": 16,
        "arabic": "وَنَحْنُ أَقْرَبُ إِلَيْهِ مِنْ حَبْلِ الْوَرِيدِ",
        "english": "And We are closer to him than his jugular vein.",
        "urdu": "اور ہم اس کی شہ رگ سے بھی زیادہ قریب ہیں۔",
        "reflection": "Allah is closer to you than your own heartbeat. You are deeply known and never forgotten.",
        "moods": ["lonely", "sad", "broken", "lost", "isolated"],
        "keywords": "closer jugular vein near intimate known present alone lonely",
    },

    # --- FEAR / COURAGE ---
    {
        "id": 23,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 155,
        "arabic": "وَبَشِّرِ الصَّابِرِينَ",
        "english": "And give good tidings to the patient.",
        "urdu": "اور صبر کرنے والوں کو خوشخبری دے دو۔",
        "reflection": "Allah personally sends good news to those who stay patient. Your patience is seen and celebrated.",
        "moods": ["scared", "fearful", "anxious", "worried", "struggling"],
        "keywords": "good tidings patient glad tidings patient reward promise",
    },
    {
        "id": 24,
        "surah_name": "Al-Imran",
        "surah_number": 3,
        "ayah": 173,
        "arabic": "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        "english": "Allah is sufficient for us, and He is the best disposer of affairs.",
        "urdu": "اللہ ہمارے لیے کافی ہے اور وہ بہترین کارساز ہے۔",
        "reflection": "When everything feels out of control — say this. It is the dua of courage and complete trust.",
        "moods": ["scared", "fearful", "anxious", "stressed", "overwhelmed"],
        "keywords": "sufficient best disposer affairs trust fear courage enough Allah wakeel",
    },

    # --- REPENTANCE / GUILT ---
    {
        "id": 25,
        "surah_name": "Al-Baqarah",
        "surah_number": 2,
        "ayah": 222,
        "arabic": "إِنَّ اللَّهَ يُحِبُّ التَّوَّابِينَ",
        "english": "Indeed, Allah loves those who are constantly repentant.",
        "urdu": "بے شک اللہ توبہ کرنے والوں سے محبت کرتا ہے۔",
        "reflection": "Repentance doesn't push Allah away — it draws you closer. He loves those who return to Him.",
        "moods": ["guilty", "regret", "shame", "broken", "repentant"],
        "keywords": "repentant tawbah love Allah return forgiveness guilty shame",
    },
    {
        "id": 26,
        "surah_name": "An-Nisa",
        "surah_number": 4,
        "ayah": 110,
        "arabic": "وَمَن يَعْمَلْ سُوءًا أَوْ يَظْلِمْ نَفْسَهُ ثُمَّ يَسْتَغْفِرِ اللَّهَ يَجِدِ اللَّهَ غَفُورًا رَّحِيمًا",
        "english": "Whoever does evil or wrongs himself but then seeks forgiveness of Allah will find Allah forgiving and merciful.",
        "urdu": "اور جو کوئی برا کام کرے یا اپنے نفس پر ظلم کرے پھر اللہ سے مغفرت مانگے تو اللہ کو بخشنے والا مہربان پائے گا۔",
        "reflection": "No sin is too great. No past too dark. Seek forgiveness and find Allah waiting for you.",
        "moods": ["guilty", "regret", "shame", "broken", "repentant", "hopeless"],
        "keywords": "evil wrong forgiveness merciful seek Allah ghafoor raheem guilt",
    },

    # --- PURPOSE / MEANING ---
    {
        "id": 27,
        "surah_name": "Adh-Dhariyat",
        "surah_number": 51,
        "ayah": 56,
        "arabic": "وَمَا خَلَقْتُ الْجِنَّ وَالْإِنسَ إِلَّا لِيَعْبُدُونِ",
        "english": "And I did not create the jinn and mankind except to worship Me.",
        "urdu": "اور میں نے جن اور انسانوں کو صرف اس لیے پیدا کیا کہ وہ میری عبادت کریں۔",
        "reflection": "You were created with divine purpose. You are not an accident. Your existence has meaning.",
        "moods": ["lost", "purposeless", "empty", "confused", "seeking"],
        "keywords": "created purpose worship jinn mankind meaning reason existence",
    },
    {
        "id": 28,
        "surah_name": "At-Tin",
        "surah_number": 95,
        "ayah": 4,
        "arabic": "لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ",
        "english": "We have certainly created man in the best of stature.",
        "urdu": "ہم نے انسان کو بہترین صورت میں پیدا کیا ہے۔",
        "reflection": "You were made in the most perfect form. When you doubt yourself, remember: Allah made you beautifully.",
        "moods": ["lost", "low self-esteem", "purposeless", "sad", "broken"],
        "keywords": "created best stature human form beautiful perfect dignity worth",
    },

    # --- HOPE ---
    {
        "id": 29,
        "surah_name": "Yusuf",
        "surah_number": 12,
        "ayah": 87,
        "arabic": "لَا تَيْأَسُوا مِن رَّوْحِ اللَّهِ",
        "english": "Do not despair of relief from Allah.",
        "urdu": "اللہ کی رحمت سے مایوس مت ہو۔",
        "reflection": "Prophet Yaqub said this after years of grief. Hope is never irrational when it is placed in Allah.",
        "moods": ["hopeless", "sad", "lost", "broken", "desperate"],
        "keywords": "despair relief hope Allah mercy rahma hopeless comfort",
    },
    {
        "id": 30,
        "surah_name": "Al-Fajr",
        "surah_number": 89,
        "ayah": "27-28",
        "arabic": "يَا أَيَّتُهَا النَّفْسُ الْمُطْمَئِنَّةُ ارْجِعِي إِلَىٰ رَبِّكِ رَاضِيَةً مَّرْضِيَّةً",
        "english": "O tranquil soul, return to your Lord, well-pleased and pleasing to Him.",
        "urdu": "اے اطمینان والی جان، اپنے رب کی طرف لوٹ آ، خوش ہو کر اور خوش کی گئی۔",
        "reflection": "The ultimate destination is peace — returning to Allah fully at rest. Let this be your direction.",
        "moods": ["peaceful", "content", "grateful", "reflective", "spiritual"],
        "keywords": "tranquil soul peace return Lord pleased spiritual calm rest",
    },
]


def get_all_moods():
    """Return all unique moods from dataset."""
    moods = set()
    for v in VERSES:
        moods.update(v["moods"])
    return sorted(moods)


def get_verses_for_mood(mood, top_n=5):
    """Simple filter by mood tag."""
    results = [v for v in VERSES if mood.lower() in [m.lower() for m in v["moods"]]]
    return results[:top_n] if results else VERSES[:top_n]
